// ── Assessment / academics types ──────────────────────────────────────────────

export const SUBGROUP_LABELS: Record<string, string> = {
  all: 'All Students',
  white: 'White',
  hispanic: 'Hispanic or Latino',
  asian: 'Asian',
  black: 'Black or African American',
  multiracial: 'Two or More Races',
  low_income: 'Low-Income',
  english_learner: 'English Learners',
  special_ed: 'Students with Disabilities',
  native_american: 'American Indian / Alaska Native',
  filipino: 'Filipino',
  pacific_islander: 'Pacific Islander',
}

export interface SubjectAcademics {
  subject: 'math' | 'ela'
  schoolYear: string
  pctProficient: number | null
  studentsTested: number | null
  yoyChange: number | null   // change in percentage points vs prior year; null if no prior data
  byGrade: { grade: string; pctProficient: number | null; studentsTested: number | null }[]
  bySubgroup: {
    subgroup: string
    label: string
    pctProficient: number | null
    studentsTested: number | null
    yoyChange: number | null
  }[]
  trend: { schoolYear: string; pctProficient: number | null }[]  // oldest → newest
}

export interface AcademicsData {
  hasData: boolean
  source: string | null
  schoolYear: string | null
  math: SubjectAcademics | null
  ela: SubjectAcademics | null
}

// ── School ────────────────────────────────────────────────────────────────────

export interface School {
  id: string
  name: string
  slug: string
  type: 'public' | 'charter' | 'private' | 'magnet'
  district: string
  state: string
  city: string
  zip: string
  address: string
  lat: number
  lng: number
  website: string
  grades: string
  enrollment: number
  studentTeacherRatio: string
  ratings: {
    greatSchools: number | null
    niche: string | null
    stateRanking: string | null
  }
  academics: {
    mathProficiency: number | null
    readingProficiency: number | null
  }
  demographics: {
    white: number
    hispanic: number
    asian: number
    black: number
    multiracial: number
    other: number
  }
  freeReducedLunchPct: number
  titleOne: boolean
  programs: {
    gate: boolean
    stem: boolean
    specialEd: boolean
    specialEdDetails: string
    dualLanguage: boolean
  }
  financials: {
    tuition: number | null
    expectedDonation: string | null
    ptaActive: boolean
  }
  enrollment_info: {
    permitPercent: string
    neighborhoodPercent: string
    tourDates: string[]
    enrollmentOpens: string
  }
  feederMap: {
    feedsInto: string[]
    feedsFrom: string[]
  }
  sentiment: {
    score: number
    reviewCount: number
    trend: 'rising' | 'stable' | 'declining'
    themes: string[]
  }
  keyInsight: string
  lastUpdated: string
  greatschoolsUrl?: string
  nicheUrl?: string
  /** YoY trend from assessment_scores — present only in search results when data available */
  trends?: {
    mathYoyChange: number | null
    readingYoyChange: number | null
  } | null
  /** Latest high-impact board insight — present only in search results when data available */
  latestIntel?: {
    headline: string
    category: string
    impact_level: string
  } | null
  /** Full HTML research report generated by Claude — stored in schools.deep_report */
  deepReport?: string | null
  /** Structured report JSON — stored in schools.report_data */
  reportData?: ReportData | null
}

// ── Report Data Types ─────────────────────────────────────────────────────────

export interface ReportHero {
  street_view_query: string
  heading?: number
  fov?: number
}

export interface ReportQuickStat {
  label: string
  value: string
  accent: boolean
}

export interface ParagraphBlock {
  type: 'paragraph'
  text: string
  has_bold?: boolean
}
export interface HeadingBlock {
  type: 'heading'
  text: string
}
export interface CalloutBlock {
  type: 'callout'
  variant: 'green' | 'amber' | 'red' | 'sky'
  label: string
  text: string
}
export interface StatItem {
  label: string
  value: string
  context: string
  green: boolean
}
export interface StatsGridBlock {
  type: 'stats_grid'
  items: StatItem[]
}
export interface ScoreBarItem {
  label: string
  pct: number
  color: 'green' | 'sky' | 'honey' | 'peach' | 'gray'
}
export interface ScoreBarsBlock {
  type: 'score_bars'
  items: ScoreBarItem[]
  source?: string
  wide_labels?: boolean
}
export interface PhotoBlock {
  type: 'photo'
  src: string
  alt: string
  caption: string
}
export interface PhotoGridBlock {
  type: 'photo_grid'
  photos: Array<{ src: string; alt: string; caption: string }>
}
export interface FeederSchool {
  name: string
  level: 'current' | 'middle' | 'high'
  detail: string
  is_or?: boolean
  slug?: string
}
export interface FeederFlowBlock {
  type: 'feeder_flow'
  schools: FeederSchool[]
}
export interface ComparisonRow {
  cells: string[]
  highlight?: boolean
  slug?: string  // slug for the school in cells[0], enables a clickable link
}
export interface ComparisonTableBlock {
  type: 'comparison_table'
  columns: string[]
  rows: ComparisonRow[]
}
export interface TourQuestionsBlock {
  type: 'tour_questions'
  title: string
  subtitle: string
  questions: string[]
}
export interface TimelineBlock {
  type: 'timeline'
  items: Array<{ date: string; text: string }>
}
export interface SectionDividerBlock {
  type: 'section_divider'
}

export type ContentBlock =
  | ParagraphBlock
  | HeadingBlock
  | CalloutBlock
  | StatsGridBlock
  | ScoreBarsBlock
  | PhotoBlock
  | PhotoGridBlock
  | FeederFlowBlock
  | ComparisonTableBlock
  | TourQuestionsBlock
  | TimelineBlock
  | SectionDividerBlock

export interface ReportSection {
  id: string
  number: number
  tag: string
  title: string
  subtitle: string
  content: ContentBlock[]
}

export interface ReportVerdict {
  paragraphs: string[]
  best_for: string
  consider_alternatives: string
}

export interface AlertItem {
  icon: string  // 'calendar' | 'construction' | 'star' | any emoji/key
  title: string
  text: string
  cta_text?: string
  cta_url?: string
}

export interface RelatedSchoolItem {
  name: string
  slug: string
  tag: string
}

/** Extra preview content shown to unauthenticated visitors on guide pages. */
export interface GuidePreviewExtras {
  callout?: CalloutBlock
  comparison_table?: ComparisonTableBlock
  calendar?: {
    title: string
    subtitle?: string
    columns: string[]
    visible_rows: ComparisonRow[]
    blurred_rows: ComparisonRow[]
  }
  contacts?: {
    title: string
    visible_blocks: ContentBlock[]
  }
}

export interface ReportData {
  generated_at: string
  version: number
  hero: ReportHero
  quick_stats: ReportQuickStat[]
  sections: ReportSection[]
  verdict: ReportVerdict
  alerts?: AlertItem[]
  related_schools?: RelatedSchoolItem[]
  /** Set server-side on gated guide pages to preserve the real chapter count
   *  after sections are stripped to slice(0,1) for unauthenticated visitors. */
  total_sections?: number
  /** Pre-computed read time (minutes) — preserved on gated guide pages so the
   *  hero badge reflects the full report even when sections are stripped. */
  _guide_read_time?: number
  /** Pre-computed source count — preserved on gated guide pages. */
  _guide_source_count?: number
  /** Strategic preview content extracted server-side for unauthenticated guide visitors. */
  _guide_preview_extras?: GuidePreviewExtras
}

export interface TourDate {
  id: number
  school_id: string
  district_id: string | null
  event_type: 'tour' | 'open_house' | 'tk_k_roundup' | 'info_session' | 'enrollment'
  title: string
  date: string | null       // ISO "2027-01-22"
  time: string | null       // "9:00 AM - 11:00 AM"
  end_date: string | null
  is_recurring: boolean
  recurrence_note: string | null
  location: string | null
  rsvp_required: boolean
  rsvp_url: string | null
  notes: string | null
  source_url: string
  scraped_at: string
  school_year: string | null
  // joined from schools table when fetched via tour-dates?zip=
  schools?: { name: string; slug: string; address: string; city: string } | null
}

// ── Board meeting insights ────────────────────────────────────────────────────

export interface BoardInsight {
  id: number
  district_id: string
  school_id: string | null
  school_name: string | null
  category: 'construction' | 'budget' | 'programs' | 'staffing' | 'policy' | 'enrollment' | 'safety' | 'other'
  headline: string
  detail: string | null
  sentiment: 'positive' | 'neutral' | 'negative'
  impact_level: 'high' | 'medium' | 'low'
  meeting_date: string | null
  district_name: string | null
  source_url: string | null
}

export interface DistrictIntelData {
  hasData: boolean
  districtName: string | null
  insights: BoardInsight[]          // school-specific insights
  districtInsights: BoardInsight[]  // district-wide insights
}

// ── Review summaries ─────────────────────────────────────────────────────────

export interface ReviewSummary {
  themes: string[]
  summary: string
  positives: string[]
  concerns: string[]
  vibe: string
  reviewCount: number
  sources: string[]
  generatedAt: string
}

export interface ReviewSummaryResponse {
  hasData: boolean
  summary?: ReviewSummary
  stale?: boolean
}

// ── Reddit summaries ──────────────────────────────────────────────────────────

export interface RedditSummary {
  themes: string[]
  summary: string
  overallSentiment: 'positive' | 'negative' | 'mixed' | 'neutral'
  mentionCount: number
  subredditsFound: string[]
  notableThreads: { title: string; url: string; score: number }[]
  generatedAt: string
}

export interface RedditSummaryResponse {
  hasData: boolean
  summary?: RedditSummary
}

// ── Parent contributions ──────────────────────────────────────────────────────

export interface Contribution {
  id: number
  userId: string
  displayName: string
  schoolId: string
  contributionType: 'review' | 'tour_report' | 'tip' | 'correction'
  rating: number | null
  title: string | null
  content: string
  tourDate: string | null
  helpfulCount: number
  createdAt: string
  hasVoted?: boolean
}

export interface ContributionResponse {
  contributions: Contribution[]
  total: number
}

export interface Subscriber {
  id: string
  email: string
  firstName: string | null
  lastName: string | null
  zip: string | null
  plan: 'free' | 'weekend' | 'school' | 'bundle'
  stripeCustomerId: string | null
  stripeSubscriptionId: string | null
  createdAt: string
  updatedAt: string
}
